name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Publish
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: mo.cyezoi.com
          CONFIG_FILE: mkdocs.yml
